group: edge
dist: trusty

env:
  global:
    TERM=dumb

language: java
jdk:
  - openjdk8
  - oraclejdk8

install: true
before_install:
  # install latest docker
  - sudo apt remove docker docker-engine docker.io
  - sudo apt update
  - >
    sudo apt install -y \
        linux-image-extra-$(uname -r) \
        linux-image-extra-virtual
  - >
    sudo apt install -y \
        apt-transport-https \
        ca-certificates \
        curl \
        software-properties-common

  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo apt-key fingerprint 0EBFCD88
  - >
    sudo add-apt-repository \
       "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
       $(lsb_release -cs) \
       stable"

  - sudo apt update -y
  - sudo apt install -y docker-ce
  - sudo apt-cache madison docker-ce

  # docker-compose, curl, jq and httpie
  - sudo apt install -y docker python-pip jq
  - sudo pip install docker-compose httpie
  - sudo usermod -aG docker $(whoami)

  # kill whatever ports is running
  - sudo kill $(sudo lsof -t -i:5432) | true
  - sudo kill $(sudo lsof -t -i:5672) | true
  - sudo kill $(sudo lsof -t -i:27017) | true
  - sudo kill $(sudo lsof -t -i:8080) | true

  - docker -v
  - docker-compose -v

script:
  - bash gradlew clean build asciidoctor

  - export parent=$(pwd)

  - cd $parent/main-swarm-static-content
  - bash gradlew clean build
  - docker-compose up --force-recreate -d --build --remove-orphans
  - sleep 30
  - http :8080
  - docker-compose down -v

  - cd $parent/main-swarm-rest-api
  - bash gradlew clean build
  - docker-compose up --force-recreate -d --build --remove-orphans
  - sleep 30
  - http :8080
  - http :8080/api
  - http :8080/api/max
  - http post :8080/api/cors max=max
  - docker-compose down -v

  - cd $parent/kotlin-plugins-java-ee
  - bash gradlew clean build
  - docker-compose up --force-recreate -d --build --remove-orphans
  - sleep 30
  - http :8080
  - http :8080/hi
  - http :8080/max
  - docker-compose down -v

  - cd $parent/kotlin-java-ee
  - bash gradlew clean build
  - java -Djava.net.preferIPv4Stack=true -jar build/libs/*-swarm.jar &
  - sleep 30
  - http :8080
  - http :8080/max
  - sudo killall -9 java | sudo kill $(sudo lsof -t -i:8080) | true

##  - cd $parent/java-kube-ee
##  - cd $parent/wildfly-swarm-gradle
#
#  - >
#    for gradle_subproject in \
#      java-kube-ee \
#      wildfly-swarm-gradle \
#    ; do
#
#      cd ${parent}/${gradle_subproject}
#      bash gradlew clean build wildfly-swarm-package
#      java -Djava.net.preferIPv4Stack=true -jar build/libs/*-swarm.jar &
#      sleep 20
#      http :8080
#      sleep 1
#      killall -9 java
#      bash docker/bin/test-dockerfile.bash
#      bash docker/bin/test-docker-compose.bash
#      bash docker/bin/test-stack-deploy.bash
#      bash mvnw clean install
#    done

  - >
    for maven_subproject in \
      kotlin-java-ee \
      wildfly-swarm-maven \
    ; do

      cd ${parent}/${maven_subproject}
      bash mvnw clean install
      #bash mvnw -Djava.net.preferIPv4Stack=true wildfly-swarm:run &
      java -Djava.net.preferIPv4Stack=true -jar target/*-swarm.jar &
      sleep 20
      http :8080
      sleep 1
      killall -9 java
      bash docker/bin/test-dockerfile.bash
      bash docker/bin/test-docker-compose.bash
      # sometimes docker swarm for some reasons not working here as 2nd, 3rd, ...
      bash docker/bin/test-stack-deploy.bash
      bash gradlew clean build wildfly-swarm-package
    done

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
