group: edge
dist: trusty

env:
  global:
    TERM=dumb

language: java
jdk:
  - openjdk8
  - oraclejdk8

install: true
before_install:
  # install latest docker
  - sudo apt remove docker docker-engine docker.io
  - sudo apt update
  - >
    sudo apt install -y \
        linux-image-extra-$(uname -r) \
        linux-image-extra-virtual
  - >
    sudo apt install -y \
        apt-transport-https \
        ca-certificates \
        curl \
        software-properties-common

  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo apt-key fingerprint 0EBFCD88
  - >
    sudo add-apt-repository \
       "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
       $(lsb_release -cs) \
       stable"

  - sudo apt update -y
  - sudo apt install -y docker-ce
  - sudo apt-cache madison docker-ce

  # docker-compose, curl, jq and httpie
  - sudo apt install -y docker python-pip jq curl
  - sudo pip install docker-compose httpie
  - sudo usermod -aG docker $(whoami)

  - source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)

  # kill whatever ports is running
  - stop_any 5432 5672 27017 8080

  - docker -v
  - docker-compose -v

script:
  - bash gradlew clean build docs

  - export parent=$(pwd)

  - cd $parent/kotlin-java-ee-2
  - bash gradlew clean build
  - java -Djava.net.preferIPv4Stack=true -jar build/libs/*-swarm.jar &
  - wait_for 8080
  - sleep 5
  - http :8080
  - http :8080/max
  - stop_any 8080
  - bash gradlew clean build
  - docker-compose up --force-recreate -d --build --remove-orphans
  - wait_for 8080
  - sleep 5
  - http :8080
  - http :8080/max
  - docker-compose down -v

  - cd $parent/main-swarm-rest-api
  - bash mvnw clean package
  - docker-compose build --force-rm --no-cache
  - docker-compose up --remove-orphans -d
  - wait_for 8080
  - sleep 5
  - http :8080
  - http :8080/api
  - http :8080/api/max
  - echo '{"users":{"username":"Max"}}' | http :8080/api/jsonp/json-pointer
  - http post :8080/api/cors max=max
  - docker-compose down -v

  - cd $parent/main-swarm-static-content
  - bash gradlew clean build
  - docker-compose up --force-recreate -d --build --remove-orphans
  - wait_for 8080
  - sleep 5
  - http :8080
  - docker-compose down -v

  - cd $parent/kotlin-plugins-java-ee
  - bash gradlew clean build
  - docker-compose up --force-recreate -d --build --remove-orphans
  - wait_for 8080
  - sleep 5
  - http :8080
  - http :8080/hi
  - http :8080/max
  - docker-compose down -v

  - cd $parent/kotlin-java-ee
  - bash gradlew clean build
  - java -Djava.net.preferIPv4Stack=true -jar build/libs/*-swarm.jar &
  - wait_for 8080
  - sleep 5
  - http :8080
  - http :8080/max
  - stop_any 8080

##  - cd $parent/java-kube-ee
##  - cd $parent/wildfly-swarm-gradle
#
#  - >
#    for gradle_subproject in \
#      java-kube-ee \
#      wildfly-swarm-gradle \
#    ; do
#
#      cd ${parent}/${gradle_subproject}
#      bash gradlew clean build wildfly-swarm-package
#      java -Djava.net.preferIPv4Stack=true -jar build/libs/*-swarm.jar &
#      wait_for 8080
#      sleep 5
#      http :8080
#      sleep 1
#      stop_any 8080
#      bash docker/bin/test-dockerfile.bash
#      bash docker/bin/test-docker-compose.bash
#      bash docker/bin/test-stack-deploy.bash
#      bash mvnw clean install
#    done

  - >
    for maven_subproject in \
      java-kube-ee \
      wildfly-swarm-maven \
    ; do

      cd ${parent}/${maven_subproject}
      bash mvnw clean install
      #bash mvnw -Djava.net.preferIPv4Stack=true wildfly-swarm:run &
      java -Djava.net.preferIPv4Stack=true -jar target/*-swarm.jar &
      wait_for 8080
      sleep 5
      http :8080
      sleep 1
      stop_any 8080
      bash docker/bin/test-dockerfile.bash
      bash docker/bin/test-docker-compose.bash
      # sometimes docker swarm for some reasons not working here as 2nd, 3rd, ...
      bash docker/bin/test-stack-deploy.bash
      bash gradlew clean build wildfly-swarm-package
    done

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
