version: "2.1"

services:

  javaee-6-ws-app:
    restart: unless-stopped
    build: .
    volumes: ["javaee-6-ws-app-data:/opt/jboss/wildfly/standalone"]
    ports:
      - "8080:8080"
      - "9990:9990"
    networks: [backing-services]

volumes:
  javaee-6-ws-app-data: {}

networks:
  backing-services:
    driver: bridge
