version: "2.1"

services:

  glassfish-extjs:
    build: .
    volumes: ["glassfish-extjs-data:/home"]
    ports:
    - "8080:8080"
    - "9990:9990"
    networks: [backing-services]
    #restart: unless-stopped

volumes:
  glassfish-extjs-data: {}

networks:
  backing-services:
    driver: bridge
