version: '2.1'
services:
  postgres:
    image: healthcheck/postgres:alpine
    restart: unless-stopped
    ports: ["5432:5432"]
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      my-app.com:
        aliases:
          - db
          - postgres
          - db.my-app.com
          - postgres.my-app.com
  jboss:
    depends_on:
      postgres:
        condition: service_healthy
    build: .
    restart: unless-stopped
    ports:
      - '5005:5005'
      - '8080:8080'
      - '9990:9990'
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db.my-app.com
    networks:
      my-app.com:
        aliases:
          - app
          - jboss
          - app.my-app.com
          - jboss.my-app.com
networks:
  my-app.com:
    driver: bridge
