version: '2.1'
services:
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    #ports: ['5432:5432']
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      my-app.com:
        aliases:
          - db
          - postgres
          - db.my-app.com
          - postgres.my-app.com
    healthcheck:
      test: pg_isready --host=127.0.0.1 --port=5432 --username=$$POSTGRES_USER --dbname=$$POSTGRES_DB
      timeout: 6s
      retries: 66
      interval: 3s
  jboss:
    depends_on:
      postgres:
        condition: service_healthy
    build: .
    restart: unless-stopped
    ports: ['8080:8080']
    #ports:
    #  - '5005:5005'
    #  - '8080:8080'
    #  - '9990:9990'
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db.my-app.com
    networks:
      my-app.com:
        aliases:
          - app
          - jboss
          - app.my-app.com
          - jboss.my-app.com
    healthcheck:
      test: wget -q --spider http://127.0.0.1:8080/app/health || exit 1
      timeout: 6s
      retries: 66
      interval: 6s
networks:
  my-app.com:
    driver: bridge
