env:
  global:
  - TERM=dumb

language: java
jdk: oraclejdk8

install: true
before_install:
- sudo apt -y update || true >/dev/null 2>&1
- sudo apt install -y --no-install-recommends wget bash curl jq libxml2-utils docker-ce python-pip >/dev/null 2>&1
- sudo pip install docker-compose httpie >/dev/null 2>&1
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 5432 5672 27017 8080 80

script:

# faces gradle
- export parent=$(pwd)
- cd ${parent}/faces
- bash ./gradlew >/dev/null 2>&1
- bash ./gradlew composeUp >/dev/null 2>&1
- http :9990/console/index.html
- http :8080/app/
- bash ./gradlew composeDown >/dev/null 2>&1

# faces maven
- bash ./mvnw >/dev/null 2>&1
- bash ./mvnw clean package com.dkanejs.maven.plugins:docker-compose-maven-plugin:1.0.1:up >/dev/null 2>&1
- docker logs -f faces_maven-faces-app_1 &
- sleep 40
- http --verify=no https://127.0.0.1:4848/
- http :8080/app/
- bash ./mvnw com.dkanejs.maven.plugins:docker-compose-maven-plugin:1.0.1:down >/dev/null 2>&1

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
