version: "2.1"

services:

  ejb-2-starter:
    restart: unless-stopped
    build: .
    volumes: ["ejb-2-starter-data:/home/app"]
    ports:
      - "5005:5005"
      - "8080:8080"
      - "8081:8081"
      - "9990:9990"
    networks: [backing-services]

volumes:
  ejb-2-starter-data: {}

networks:
  backing-services:
    driver: bridge
