version: "2.1"

services:

  app:
    restart: unless-stopped
    build:
      context: ../..
      dockerfile: ./docker/src/Dockerfile
    volumes: ["app-data:/opt/app"]
    ports: ["8080:8080"]
    networks: [backing-services]

volumes:
  app-data: {}

networks:
  backing-services:
    driver: bridge
